# docker-compose.yml
version: '3.8'

services:
  db:
    container_name: database_prod
    image: postgres:15
    ports:
      - "${DATABASE_PORT}:5432"
    env_file: ${ENV_FILE:-.env}  # Usa .env por defecto
    environment:
      PGPASSFILE: /run/secrets/pgpass
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    profiles:
      - prod

  db_dev:
    container_name: database_dev
    image: postgres:15
    ports:
      - "${DATABASE_PORT}:5432"  # Puerto diferente para desarrollo
    env_file: dev.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    profiles:
      - dev

  api:
    container_name: api_${APP_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: ${ENV_FILE:-.env}
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT:-5434}/${DATABASE_NAME}
      - RUST_LOG=debug
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://${DATABASE_HOST}:${SERVER_PORT}/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    profiles:
      - ${APP_ENV:-prod}


volumes:
  postgres_data_prod:
  postgres_data_dev:

networks:
  app-network:
    driver: bridge